spring:
  application:
    name: kuroline-chat-ms
  servlet:
    multipart:
      max-file-size: 3MB
server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
